### ISSUE TITLE
Server Side Events

### ISSUE THREAD

**Issue by kesavkolla** [DrNickMartin/websocket-broadcasting#1]
Is it possible to use SSE instead of websockets?  I'd love to see some example with FastAPI and SSE

**Comment by doc-nicole** [comment]
Out of interest, why would you want to use SSE instead of WebSockets. With WS you get bi- directional communication.

**Comment by kesavkolla** [comment]
SSE is good when server wants to send realtime updates to client.  Some of the usecases best achieved with SSE as there is no communication from client.

**Comment by slushnys** [comment]
@kesavkolla isn't that exactly what websockets do? You just register a connection and can send bytes to the registered clients.

**Comment by doc-nicole** [comment]
@kesavkolla you might be interested in this article that uses a Starlette SSE library:
https://sairamkrish.medium.com/handling-server-send-events-with-python-fastapi-e578f3929af1
